# Generated by Django 2.0.5 on 2022-01-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltable',
            options={'verbose_name': '技能', 'verbose_name_plural': '技能'},
        ),
    ]
